In [1]:
import numpy as np   # numercal python. 수치 해석
import pandas as pd   # DataFrame을 쉽게 다루기

import matplotlib.pyplot as plt   # Data visualization
import seaborn as sns   # Data visualization
sns.set_style("whitegrid")   # Seaborn 스타일 설정
sns.set(font_scale = 2.0)   # seaborn 라이브러리 세팅 (plot의 모든 폰트 사이즈를 2.0로 지정)

import missingno as msno   # 데이터셋에 채워지지 않은 null 데이터를 쉽게 보여줄 수 있는 라이브러리

import warnings 
warnings.filterwarnings('ignore')   # ignore warning

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

ts = pd.read_csv('ts_prepro_wo_NLP.csv')
ts.head(10)

Date  PPXDK00/FO 380 CST 3.5%S FOB Spore Cargo/CLOSE  \
0  2022-01-04                                          434.04   
1  2022-01-04                                          434.04   
2  2022-01-05                                          436.28   
3  2022-01-06                                          438.37   
4  2022-01-07                                          450.78   
5  2022-01-10                                          448.57   
6  2022-01-11                                          446.39   
7  2022-01-12                                          459.03   
8  2022-01-13                                          463.10   
9  2022-01-14                                          463.62   

   PUABC00/FO 3.5%S FOB Rdam Barge/CLOSE  \
0                                 430.50   
1                                 430.50   
2                                 437.75   
3                                 444.00   
4                                 442.00   
5                                 437.25   
6                                 446.00   
7                                 453.50   
8                                 453.50   
9                                 460.75   

   PUAFT00/Bunker FO 380 CST Dlvd Singapore/CLOSE  \
0                                           447.0   
1                                           447.0   
2                                           449.0   
3                                           451.0   
4                                           463.0   
5                                           461.0   
6                                           459.0   
7                                           472.0   
8                                           476.0   
9                                           477.0   

   AALMZ00/Marine Gasoil 0.5% Dlvd Singapore/CLOSE  \
0                                            684.0   
1                                            684.0   
2                                            694.0   
3                                            698.0   
4                                            709.0   
5                                            712.0   
6                                            712.0   
7                                            729.0   
8                                            737.0   
9                                            747.0   

   PUAFN00/Bunker FO 380 CST 3.5% Dlvd Rotterdam/CLOSE  \
0                                              439.0     
1                                              439.0     
2                                              445.0     
3                                              456.0     
4                                              456.0     
5                                              451.0     
6                                              462.0     
7                                              464.0     
8                                              463.0     
9                                              466.0     

   AAYWT00/Gasoil .1%S (1000ppm) FOB ARA Barge (NextGen MOC)/CLOSE  \
0                                             672.25                 
1                                             672.25                 
2                                             692.25                 
3                                             701.25                 
4                                             702.25                 
5                                             698.75                 
6                                             714.50                 
7                                             727.50                 
8                                             727.75                 
9                                             738.75                 

   AARTG00/Marine Gasoil 0.1% Dlvd Rotterdam/CLOSE  \
0                                            670.0   
1                                            670.0   
2                                            685.0   
3  

In [3]:
data = pd.DataFrame(ts.columns[1:], columns = ["Info"])
data.head()

Info
0     PPXDK00/FO 380 CST 3.5%S FOB Spore Cargo/CLOSE
1              PUABC00/FO 3.5%S FOB Rdam Barge/CLOSE
2     PUAFT00/Bunker FO 380 CST Dlvd Singapore/CLOSE
3    AALMZ00/Marine Gasoil 0.5% Dlvd Singapore/CLOSE
4  PUAFN00/Bunker FO 380 CST 3.5% Dlvd Rotterdam/...

In [4]:
# '/'를 기준으로 분리하고 적절히 처리
data[['Code', 'Assessment', 'Statistics']] = data['Info'].str.split('/', expand=True, n=2)

# 'Statistics' 열에 NaN 값이 있는지 확인하고 기본값 설정
data['Statistics'] = data['Statistics'].fillna("Not Available")
data

Info     Code  \
0      PPXDK00/FO 380 CST 3.5%S FOB Spore Cargo/CLOSE  PPXDK00   
1               PUABC00/FO 3.5%S FOB Rdam Barge/CLOSE  PUABC00   
2      PUAFT00/Bunker FO 380 CST Dlvd Singapore/CLOSE  PUAFT00   
3     AALMZ00/Marine Gasoil 0.5% Dlvd Singapore/CLOSE  AALMZ00   
4   PUAFN00/Bunker FO 380 CST 3.5% Dlvd Rotterdam/...  PUAFN00   
5   AAYWT00/Gasoil .1%S (1000ppm) FOB ARA Barge (N...  AAYWT00   
6     AARTG00/Marine Gasoil 0.1% Dlvd Rotterdam/CLOSE  AARTG00   
7       AARKD00/Bunker FO 380 CST Dlvd Shanghai/CLOSE  AARKD00   
8      AARKE00/Marine Gasoil 0.5% Dlvd Shanghai/CLOSE  AARKE00   
9   PUAFL00/Bunker FO 380 CST 3.5% Dlvd Piraeus/CLOSE  PUAFL00   
10      POADG00/Marine Gasoil 0.1% Dlvd Piraeus/CLOSE  POADG00   
11     PUAER00/Bunker FO 380 CST Dlvd Hong Kong/CLOSE  PUAER00   
12  AAXYQ00/Low Sulfur Marine Gasoil 0.1% Dlvd Hon...  AAXYQ00   
13  PUAFD00/Bunker FO 380 CST 3.5% Ex-Wharf Genoa/...  PUAFD00   
14    PBABK00/Marine Gasoil 0.1% Ex-Wharf Genoa/CLOSE  PBABK00   
15         PUAGQ00/Bunker FO 380 CST Dlvd Busan/CLOSE  PUAGQ00   
16        AARKJ00/Marine Gasoil 0.5% Dlvd Busan/CLOSE  AARKJ00   
17  AAMNV00/Bunker FO 380 CST 3.5% Dlvd Charleston...  AAMNV00   
18   AAWWV00/Marine Gasoil 0.1% Dlvd Charleston/CLOSE  AAWWV00   
19  AAGPM00/Bunker FO 380 CST 3.5% Dlvd Los Angele...  AAGPM00   
20  AAWWY00/Marine Gasoil 0.1% Dlvd Los Angeles/CLOSE  AAWWY00   
21  PBAAP00/Bunker FO 380 CST 3.5% Ex-Wharf Los An...  PBAAP00   
22  AAWYR00/Marine Gasoil 0.1% Ex-Wharf Los Angele...  AAWYR00   
23  AAGPD00/Bunker FO 380 CST 3.5% Dlvd Houston/CLOSE  AAGPD00   
24      AAWWX00/Marine Gasoil 0.1% Dlvd Houston/CLOSE  AAWWX00   
25  AAGQN00/Bunker FO 380 CST 3.5% Dlvd New York/C...  AAGQN00   
26     AAWYB00/Marine Gasoil 0.1% Dlvd New York/CLOSE  AAWYB00   
27  AAGQW00/Bunker FO 380 CST 3.5% Dlvd Norfolk/CLOSE  AAGQW00   
28      AAWYC00/Marine Gasoil 0.1% Dlvd Norfolk/CLOSE  AAWYC00   
29  AAXJR00/Bunker FO 380 CST 3.5% Ex-Wharf Savann...  AAXJR00   
30  AAWZF00/Marine Gasoil 0.1% Ex-Wharf Savannah/C...  AAWZF00   
31  AAGSG00/Bunker FO 380 CST 3.5% Dlvd Seattle/CLOSE  AAGSG00   
32      AAWYL00/Marine Gasoil 0.1% Dlvd Seattle/CLOSE  AAWYL00   
33  AAKAB00/Bunker FO 380 CST 3.5% Dlvd Gibraltar/...  AAKAB00   
34    AARSU00/Marine Gasoil 0.1% Dlvd Gibraltar/CLOSE  AARSU00   
35         PUAEV00/Bunker FO 380 CST Dlvd Japan/CLOSE  PUAEV00   
36        POACI00/Marine Diesel 0.5% Dlvd Japan/CLOSE  POACI00   
37    PBABW00/Marine Gasoil 0.1% Dlvd El Callao/CLOSE  PBABW00   
38  PUAYR00/Bunker FO 380 CST 3.5% Dlvd Valparaiso...  PUAYR00   
39   PBABX00/Marine Gasoil 0.1% Dlvd Valparaiso/CLOSE  PBABX00   
40  PUBAD00/Bunker FO 380 CST 3.5% Ex-Wharf Balboa...  PUBAD00   
41  AAXWI00/Marine Gasoil 0.1% Ex-Wharf Panama Can...  AAXWI00   
42      AARKK00/Marine Gasoil 0.5% Dlvd Colombo/CLOSE  AARKK00   
43  AAWYU00/Marine Gasoil 0.1% Ex-Wharf New York/C...  AAWYU00   
44  PUAFI00/Bunker FO 380 CST 3.5% Ex-Wharf New Yo...  PUAFI00   
45  AAXYO00/Low Sulfur Marine Gasoil 0.1% Dlvd Sin...  AAXYO00   
46  AAXYR00/Low Sulfur Marine Gasoil 0.1% Dlvd Sha...  AAXYR00   
47  AAXYS00/Low Sulfur Marine Gasoil 0.1% Dlvd Sou...  AAXYS00   
48  PUAEO00/Bunker FO 380 CST 3.5% Ex-Wharf French...  PUAEO00   
49  POABX00/Marine Gasoil 0.1% Ex-Wharf French Med...  POABX00   
50   PUAGX00/Bunker FO 180 CST 3.5% Dlvd Durban/CLOSE  PUAGX00   
51            PUAGY00/Marine Gasoil Dlvd Durban/CLOSE  PUAGY00   
52  AAXYT00/Low Sulfur Marine Diesel 0.1% Dlvd Tok...  AAXYT00   
53  PUAET00/Bunker FO 380 CST 3.5% Dlvd Istanbul/C...  PUAET00   
54  AAWZE00/Marine Gasoil 0.1% Ex-Wharf San Franci...  AAWZE00   
55    AARJZ00/Bunker FO 380 CST Dlvd West Japan/CLOSE  AARJZ00   
56  AAWYF00/Marine Gasoil 0.1% Dlvd San Francisco/...  AAWYF00   
57     POACF00/Marine Gasoil 0.1% Dlvd Istanbul/CLOSE  POACF00   
58     AAVUO00/Bunker FO 500 CST Dlvd Singapore/CLOSE  AAVUO00   
59    AARSH00/Marine Gasoil 0.1% Dlvd Algeciras/CLOSE  AARSH00   
60  PUAEE00/Bunker FO 3

In [5]:
data.drop('Info', axis=1, inplace=True)
data.head()

Code                             Assessment Statistics
0  PPXDK00       FO 380 CST 3.5%S FOB Spore Cargo      CLOSE
1  PUABC00                FO 3.5%S FOB Rdam Barge      CLOSE
2  PUAFT00       Bunker FO 380 CST Dlvd Singapore      CLOSE
3  AALMZ00      Marine Gasoil 0.5% Dlvd Singapore      CLOSE
4  PUAFN00  Bunker FO 380 CST 3.5% Dlvd Rotterdam      CLOSE

In [6]:
data['Assessment'].value_counts()

Assessment
Gasoil 0.1%S CIF NWE Cargo (NextGen MOC)             3
Gasoil .1%S (1000ppm) CIF Med Cargo (NextGen MOC)    3
FO 3.5%S CIF Med Cargo                               3
Gasoil 0.1%S FOB Med Cargo (NextGen MOC)             3
FO 3.5%S FOB Med Cargo                               3
Marine Gasoil 0.1% Dlvd Malta                        3
Bunker FO 380 CST 3.5% Dlvd Malta                    3
FO 380 CST 3.5%S FOB Spore Cargo                     1
Bunker FO 180 CST 3.5% Dlvd Durban                   1
Marine Gasoil 0.1% Dlvd San Francisco                1
Bunker FO 380 CST Dlvd West Japan                    1
Marine Gasoil 0.1% Ex-Wharf San Francisco            1
Bunker FO 380 CST 3.5% Dlvd Istanbul                 1
Low Sulfur Marine Diesel 0.1% Dlvd Tokyo Bay         1
Marine Gasoil Dlvd Durban                            1
Low Sulfur Marine Gasoil 0.1% Dlvd Shanghai          1
Marine Gasoil 0.1% Ex-Wharf French Med               1
Bunker FO 380 CST 3.5% Ex-Wharf French Med           1

- 유형: "Gasoil", "Marine Gasoil", "Bunker FO", "Marine Fuel", "Marine Diesel"
- 황 함유량: ".001%S (10ppm)", "0.1%S", "0.1%", ".1%S (1000ppm)", "3.5%", "3.5%S", "0.5%"
- 동점도 (Kinematic Viscosity): 180 CST (Centistokes), 380 CST, 500 CST
    - 동점도 = 점도 X 밀도.중력의 존재 하에 나타나는 점도로서 액체의 경우 대부분 동점도를 사용함.
    - 절대 점도: 중력을 고려하지 않은 점도
- 배달 방식: "Dlvd", "FOB", "CIF", "Ex-Wharf"
- 지역: "NWE", "Med", "Los Angeles", "Singapore", "Rotterdam" 등
- 경제/시장 용어: "(NextGen MOC)", "ICE", "Settlement", "Mo01", "Mo01", "Barge"
    - NextGen MOC: 이는 특정 거래 플랫폼이나 거래 방식을 나타낼 수 있으며, 표준 거래 방식과 다를 수 있음.
    - ICE (Intercontinental Exchange): 글로벌 시장에서 에너지, 금융 상품 등을 거래하는 교환 시장
    - Settlement: 거래가 종료된 후 최종적으로 정산된 가격
    - Mo01, Mo02: 해당 거래의 월별 계약. Mo01은 첫 번째 월 계약, Mo02는 두 번째 월 계약을 의미.
    - Barge: 운송 수단이 바지선인 경우.

In [7]:
low_sulfur = data[data['Assessment'].str.contains('Low Sulfur')]
low_sulfur

Code                                      Assessment Statistics
12  AAXYQ00    Low Sulfur Marine Gasoil 0.1% Dlvd Hong Kong      CLOSE
45  AAXYO00    Low Sulfur Marine Gasoil 0.1% Dlvd Singapore      CLOSE
46  AAXYR00     Low Sulfur Marine Gasoil 0.1% Dlvd Shanghai      CLOSE
47  AAXYS00  Low Sulfur Marine Gasoil 0.1% Dlvd South Korea      CLOSE
52  AAXYT00    Low Sulfur Marine Diesel 0.1% Dlvd Tokyo Bay      CLOSE
65  AAXYP00     Low Sulfur Marine Gasoil 0.1% Dlvd Fujairah      CLOSE

전부 황함량이 0.1%이므로 'Low Sulfur'라는 키워드는 삭제한다.

In [8]:
data['Assessment'] = data['Assessment'].str.replace('Low Sulfur', '', regex=False)
data['Assessment'].str.contains('Low Sulfur').any()

False

In [9]:
def classify_fuel_type(value):
    if "Marine Gasoil" in value:
        return "Marine Gasoil"
    elif "Marine Fuel" in value:
        return "Marine Fuel"
    elif "Marine Diesel" in value:
        return "Marine Diesel"
    elif "Gasoil" in value:
        return "Gasoil"
    elif "Bunker FO" in value:
        return "Bunker Fuel Oil"
    elif "FO" in value:
        return "Fuel Oil"
    else:
        return "Other"

def classify_sulfur_content(value):
    if ".001%S (10ppm)" in value:
        return "0.001%"
    elif "0.1%S" in value:
        return "0.1%"
    elif "0.1%" in value:
        return "0.1%"
    elif ".1%S (1000ppm)" in value:
        return "0.1%"
    elif "3.5S%" in value:
        return "3.5%"
    elif "3.5%" in value:
        return "3.5%"
    elif "0.5%" in value:
        return "0.5%"
    else:
        return "Unknown"

def classify_viscosity(value):
    if "180 CST" in value:
        return "180 CST"
    elif "380 CST" in value:
        return "380 CST"
    elif "500 CST" in value:
        return "500 CST"
    else:
        return "Unknown"

def classify_delivery_type(value):
    if "Dlvd" in value:
        return "Delivered"
    elif "Bunkers Delivered" in value:
        return "Delivered"
    elif "Delivered" in value:
        return "Delivered"
    elif "FOB" in value:
        return "FOB"
    elif "CIF" in value:
        return "CIF"
    elif "Ex-Wharf" in value:
        return "Ex-Wharf"
    else:
        return "Unknown"

def classify_others(value):
    if "(NextGen MOC)" in value:
        return "NextGen MOC"
    elif "ICE" in value:
        return "ICE"
    elif "Settlement Mo01" in value:
        return "Settlement Mo01"
    elif "Settlement Mo02" in value:
        return "Settlement Mo02"
    elif "Barge" in value:
        return "Barge"
    else:
        return "None"

# 'etc' 컬럼을 위한 데이터 추출 함수
def extract_etc(value, fuel_type, sulfur_content, viscosity, delivery_type, others):
    # 사용된 분류를 제외한 나머지 텍스트 추출
    etc_text = value.replace(fuel_type, '').replace(sulfur_content, '').replace(viscosity, '').replace(delivery_type, '').replace(others, '')
    return etc_text.strip()

In [10]:
# 각 데이터 포인트를 분류
data['Fuel Type'] = data['Assessment'].apply(classify_fuel_type)
data['Sulfur Content'] = data['Assessment'].apply(classify_sulfur_content)
data['Viscosity'] = data['Assessment'].apply(classify_viscosity)
data['Delivery Type'] = data['Assessment'].apply(classify_delivery_type)
data['Others'] = data['Assessment'].apply(classify_others)

# 'etc' 컬럼 계산
data['Etc'] = data.apply(lambda x: extract_etc(x['Assessment'], x['Fuel Type'], x['Sulfur Content'], x['Viscosity'], x['Delivery Type'], x['Others']), axis=1)

data

Code                                         Assessment Statistics  \
0   PPXDK00                   FO 380 CST 3.5%S FOB Spore Cargo      CLOSE   
1   PUABC00                            FO 3.5%S FOB Rdam Barge      CLOSE   
2   PUAFT00                   Bunker FO 380 CST Dlvd Singapore      CLOSE   
3   AALMZ00                  Marine Gasoil 0.5% Dlvd Singapore      CLOSE   
4   PUAFN00              Bunker FO 380 CST 3.5% Dlvd Rotterdam      CLOSE   
5   AAYWT00  Gasoil .1%S (1000ppm) FOB ARA Barge (NextGen MOC)      CLOSE   
6   AARTG00                  Marine Gasoil 0.1% Dlvd Rotterdam      CLOSE   
7   AARKD00                    Bunker FO 380 CST Dlvd Shanghai      CLOSE   
8   AARKE00                   Marine Gasoil 0.5% Dlvd Shanghai      CLOSE   
9   PUAFL00                Bunker FO 380 CST 3.5% Dlvd Piraeus      CLOSE   
10  POADG00                    Marine Gasoil 0.1% Dlvd Piraeus      CLOSE   
11  PUAER00                   Bunker FO 380 CST Dlvd Hong Kong      CLOSE   
12  AAXYQ00                  Marine Gasoil 0.1% Dlvd Hong Kong      CLOSE   
13  PUAFD00              Bunker FO 380 CST 3.5% Ex-Wharf Genoa      CLOSE   
14  PBABK00                  Marine Gasoil 0.1% Ex-Wharf Genoa      CLOSE   
15  PUAGQ00                       Bunker FO 380 CST Dlvd Busan      CLOSE   
16  AARKJ00                      Marine Gasoil 0.5% Dlvd Busan      CLOSE   
17  AAMNV00             Bunker FO 380 CST 3.5% Dlvd Charleston      CLOSE   
18  AAWWV00                 Marine Gasoil 0.1% Dlvd Charleston      CLOSE   
19  AAGPM00            Bunker FO 380 CST 3.5% Dlvd Los Angeles      CLOSE   
20  AAWWY00                Marine Gasoil 0.1% Dlvd Los Angeles      CLOSE   
21  PBAAP00        Bunker FO 380 CST 3.5% Ex-Wharf Los Angeles      CLOSE   
22  AAWYR00            Marine Gasoil 0.1% Ex-Wharf Los Angeles      CLOSE   
23  AAGPD00                Bunker FO 380 CST 3.5% Dlvd Houston      CLOSE   
24  AAWWX00                    Marine Gasoil 0.1% Dlvd Houston      CLOSE   
25  AAGQN00               Bunker FO 380 CST 3.5% Dlvd New York      CLOSE   
26  AAWYB00                   Marine Gasoil 0.1% Dlvd New York      CLOSE   
27  AAGQW00                Bunker FO 380 CST 3.5% Dlvd Norfolk      CLOSE   
28  AAWYC00                    Marine Gasoil 0.1% Dlvd Norfolk      CLOSE   
29  AAXJR00           Bunker FO 380 CST 3.5% Ex-Wharf Savannah      CLOSE   
30  AAWZF00               Marine Gasoil 0.1% Ex-Wharf Savannah      CLOSE   
31  AAGSG00                Bunker FO 380 CST 3.5% Dlvd Seattle      CLOSE   
32  AAWYL00                    Marine Gasoil 0.1% Dlvd Seattle      CLOSE   
33  AAKAB00              Bunker FO 380 CST 3.5% Dlvd Gibraltar      CLOSE   
34  AARSU00                  Marine Gasoil 0.1% Dlvd Gibraltar      CLOSE   
35  PUAEV00                       Bunker FO 380 CST Dlvd Japan      CLOSE   
36  POACI00                      Marine Diesel 0.5% Dlvd Japan      CLOSE   
37  PBABW00                  Marine Gasoil 0.1% Dlvd El Callao      CLOSE   
38  PUAYR00             Bunker FO 380 CST 3.5% Dlvd Valparaiso      CLOSE   
39  PBABX00                 Marine Gasoil 0.1% Dlvd Valparaiso      CLOSE   
40  PUBAD00             Bunker FO 380 CST 3.5% Ex-Wharf Balboa      CLOSE   
41  AAXWI00           Marine Gasoil 0.1% Ex-Wharf Panama Canal      CLOSE   
42  AARKK00                    Marine Gasoil 0.5% Dlvd Colombo      CLOSE   
43  AAWYU00               Marine Gasoil 0.1% Ex-Wharf New York      CLOSE   
44  PUAFI00           Bunker FO 380 CST 3.5% Ex-Wharf New York      CLOSE   
45  AAXYO00                  Marine Gasoil 0.1% Dlvd Singapore      CLOSE   
46  AAXYR00                   Marine Gasoil 0.1% Dlvd Shanghai      CLOSE   
47  AAXYS00                Marine Gasoil 0.1% Dlvd South Korea      CLOSE   
48  PUAEO00         Bunker FO 380 CST 3.5% Ex-Wharf French Med      CLOSE   
49  POABX00             Marine Gasoil 0.1% Ex-Wharf French Med      CLOSE   
50  PUAGX00                 Bunker FO 180 CST 3.5% Dlvd Durban      CLOSE   
51 

In [15]:
data.rename(columns = {'Etc': 'Location'}, inplace = True)
keywords_to_remove = ['Bunker Fo', 'FO', 'S ', 'Dlvd', '.001%S (10ppm) ', '.1%S (1000ppm) ', '.1% (1000ppm)', '.1%(1000ppm)', '.001%(10ppm)',  '.001%(10ppm) ', 
                      'Bunkers', 'Bunker ', '()', ' $']

def remove_keywords(text):
    for keyword in keywords_to_remove:
        text = text.replace(keyword, '')
    return text.strip()

data['Location'] = data['Location'].apply(remove_keywords)
data

Code                                         Assessment Statistics  \
0   PPXDK00                   FO 380 CST 3.5%S FOB Spore Cargo      CLOSE   
1   PUABC00                            FO 3.5%S FOB Rdam Barge      CLOSE   
2   PUAFT00                   Bunker FO 380 CST Dlvd Singapore      CLOSE   
3   AALMZ00                  Marine Gasoil 0.5% Dlvd Singapore      CLOSE   
4   PUAFN00              Bunker FO 380 CST 3.5% Dlvd Rotterdam      CLOSE   
5   AAYWT00  Gasoil .1%S (1000ppm) FOB ARA Barge (NextGen MOC)      CLOSE   
6   AARTG00                  Marine Gasoil 0.1% Dlvd Rotterdam      CLOSE   
7   AARKD00                    Bunker FO 380 CST Dlvd Shanghai      CLOSE   
8   AARKE00                   Marine Gasoil 0.5% Dlvd Shanghai      CLOSE   
9   PUAFL00                Bunker FO 380 CST 3.5% Dlvd Piraeus      CLOSE   
10  POADG00                    Marine Gasoil 0.1% Dlvd Piraeus      CLOSE   
11  PUAER00                   Bunker FO 380 CST Dlvd Hong Kong      CLOSE   
12  AAXYQ00                  Marine Gasoil 0.1% Dlvd Hong Kong      CLOSE   
13  PUAFD00              Bunker FO 380 CST 3.5% Ex-Wharf Genoa      CLOSE   
14  PBABK00                  Marine Gasoil 0.1% Ex-Wharf Genoa      CLOSE   
15  PUAGQ00                       Bunker FO 380 CST Dlvd Busan      CLOSE   
16  AARKJ00                      Marine Gasoil 0.5% Dlvd Busan      CLOSE   
17  AAMNV00             Bunker FO 380 CST 3.5% Dlvd Charleston      CLOSE   
18  AAWWV00                 Marine Gasoil 0.1% Dlvd Charleston      CLOSE   
19  AAGPM00            Bunker FO 380 CST 3.5% Dlvd Los Angeles      CLOSE   
20  AAWWY00                Marine Gasoil 0.1% Dlvd Los Angeles      CLOSE   
21  PBAAP00        Bunker FO 380 CST 3.5% Ex-Wharf Los Angeles      CLOSE   
22  AAWYR00            Marine Gasoil 0.1% Ex-Wharf Los Angeles      CLOSE   
23  AAGPD00                Bunker FO 380 CST 3.5% Dlvd Houston      CLOSE   
24  AAWWX00                    Marine Gasoil 0.1% Dlvd Houston      CLOSE   
25  AAGQN00               Bunker FO 380 CST 3.5% Dlvd New York      CLOSE   
26  AAWYB00                   Marine Gasoil 0.1% Dlvd New York      CLOSE   
27  AAGQW00                Bunker FO 380 CST 3.5% Dlvd Norfolk      CLOSE   
28  AAWYC00                    Marine Gasoil 0.1% Dlvd Norfolk      CLOSE   
29  AAXJR00           Bunker FO 380 CST 3.5% Ex-Wharf Savannah      CLOSE   
30  AAWZF00               Marine Gasoil 0.1% Ex-Wharf Savannah      CLOSE   
31  AAGSG00                Bunker FO 380 CST 3.5% Dlvd Seattle      CLOSE   
32  AAWYL00                    Marine Gasoil 0.1% Dlvd Seattle      CLOSE   
33  AAKAB00              Bunker FO 380 CST 3.5% Dlvd Gibraltar      CLOSE   
34  AARSU00                  Marine Gasoil 0.1% Dlvd Gibraltar      CLOSE   
35  PUAEV00                       Bunker FO 380 CST Dlvd Japan      CLOSE   
36  POACI00                      Marine Diesel 0.5% Dlvd Japan      CLOSE   
37  PBABW00                  Marine Gasoil 0.1% Dlvd El Callao      CLOSE   
38  PUAYR00             Bunker FO 380 CST 3.5% Dlvd Valparaiso      CLOSE   
39  PBABX00                 Marine Gasoil 0.1% Dlvd Valparaiso      CLOSE   
40  PUBAD00             Bunker FO 380 CST 3.5% Ex-Wharf Balboa      CLOSE   
41  AAXWI00           Marine Gasoil 0.1% Ex-Wharf Panama Canal      CLOSE   
42  AARKK00                    Marine Gasoil 0.5% Dlvd Colombo      CLOSE   
43  AAWYU00               Marine Gasoil 0.1% Ex-Wharf New York      CLOSE   
44  PUAFI00           Bunker FO 380 CST 3.5% Ex-Wharf New York      CLOSE   
45  AAXYO00                  Marine Gasoil 0.1% Dlvd Singapore      CLOSE   
46  AAXYR00                   Marine Gasoil 0.1% Dlvd Shanghai      CLOSE   
47  AAXYS00                Marine Gasoil 0.1% Dlvd South Korea      CLOSE   
48  PUAEO00         Bunker FO 380 CST 3.5% Ex-Wharf French Med      CLOSE   
49  POABX00             Marine Gasoil 0.1% Ex-Wharf French Med      CLOSE   
50  PUAGX00                 Bunker FO 180 CST 3.5% Dlvd Durban      CLOSE   
51 

In [19]:
data['Statistics'] = data['Statistics'].str.replace('mt/CLOSE', 'CLOSE', regex = False)

replacement = {'Settlement Mo01': 'Singapore', 'Settlement Mo02': 'Singapore', 'Spore Cargo': 'Singapore', 'Rdam': 'Rotterdam', 'Tokyo Bay': 'Japan'}
data['Location'] = data['Location'].replace(replacement)

data

Code                                         Assessment Statistics  \
0   PPXDK00                   FO 380 CST 3.5%S FOB Spore Cargo      CLOSE   
1   PUABC00                            FO 3.5%S FOB Rdam Barge      CLOSE   
2   PUAFT00                   Bunker FO 380 CST Dlvd Singapore      CLOSE   
3   AALMZ00                  Marine Gasoil 0.5% Dlvd Singapore      CLOSE   
4   PUAFN00              Bunker FO 380 CST 3.5% Dlvd Rotterdam      CLOSE   
5   AAYWT00  Gasoil .1%S (1000ppm) FOB ARA Barge (NextGen MOC)      CLOSE   
6   AARTG00                  Marine Gasoil 0.1% Dlvd Rotterdam      CLOSE   
7   AARKD00                    Bunker FO 380 CST Dlvd Shanghai      CLOSE   
8   AARKE00                   Marine Gasoil 0.5% Dlvd Shanghai      CLOSE   
9   PUAFL00                Bunker FO 380 CST 3.5% Dlvd Piraeus      CLOSE   
10  POADG00                    Marine Gasoil 0.1% Dlvd Piraeus      CLOSE   
11  PUAER00                   Bunker FO 380 CST Dlvd Hong Kong      CLOSE   
12  AAXYQ00                  Marine Gasoil 0.1% Dlvd Hong Kong      CLOSE   
13  PUAFD00              Bunker FO 380 CST 3.5% Ex-Wharf Genoa      CLOSE   
14  PBABK00                  Marine Gasoil 0.1% Ex-Wharf Genoa      CLOSE   
15  PUAGQ00                       Bunker FO 380 CST Dlvd Busan      CLOSE   
16  AARKJ00                      Marine Gasoil 0.5% Dlvd Busan      CLOSE   
17  AAMNV00             Bunker FO 380 CST 3.5% Dlvd Charleston      CLOSE   
18  AAWWV00                 Marine Gasoil 0.1% Dlvd Charleston      CLOSE   
19  AAGPM00            Bunker FO 380 CST 3.5% Dlvd Los Angeles      CLOSE   
20  AAWWY00                Marine Gasoil 0.1% Dlvd Los Angeles      CLOSE   
21  PBAAP00        Bunker FO 380 CST 3.5% Ex-Wharf Los Angeles      CLOSE   
22  AAWYR00            Marine Gasoil 0.1% Ex-Wharf Los Angeles      CLOSE   
23  AAGPD00                Bunker FO 380 CST 3.5% Dlvd Houston      CLOSE   
24  AAWWX00                    Marine Gasoil 0.1% Dlvd Houston      CLOSE   
25  AAGQN00               Bunker FO 380 CST 3.5% Dlvd New York      CLOSE   
26  AAWYB00                   Marine Gasoil 0.1% Dlvd New York      CLOSE   
27  AAGQW00                Bunker FO 380 CST 3.5% Dlvd Norfolk      CLOSE   
28  AAWYC00                    Marine Gasoil 0.1% Dlvd Norfolk      CLOSE   
29  AAXJR00           Bunker FO 380 CST 3.5% Ex-Wharf Savannah      CLOSE   
30  AAWZF00               Marine Gasoil 0.1% Ex-Wharf Savannah      CLOSE   
31  AAGSG00                Bunker FO 380 CST 3.5% Dlvd Seattle      CLOSE   
32  AAWYL00                    Marine Gasoil 0.1% Dlvd Seattle      CLOSE   
33  AAKAB00              Bunker FO 380 CST 3.5% Dlvd Gibraltar      CLOSE   
34  AARSU00                  Marine Gasoil 0.1% Dlvd Gibraltar      CLOSE   
35  PUAEV00                       Bunker FO 380 CST Dlvd Japan      CLOSE   
36  POACI00                      Marine Diesel 0.5% Dlvd Japan      CLOSE   
37  PBABW00                  Marine Gasoil 0.1% Dlvd El Callao      CLOSE   
38  PUAYR00             Bunker FO 380 CST 3.5% Dlvd Valparaiso      CLOSE   
39  PBABX00                 Marine Gasoil 0.1% Dlvd Valparaiso      CLOSE   
40  PUBAD00             Bunker FO 380 CST 3.5% Ex-Wharf Balboa      CLOSE   
41  AAXWI00           Marine Gasoil 0.1% Ex-Wharf Panama Canal      CLOSE   
42  AARKK00                    Marine Gasoil 0.5% Dlvd Colombo      CLOSE   
43  AAWYU00               Marine Gasoil 0.1% Ex-Wharf New York      CLOSE   
44  PUAFI00           Bunker FO 380 CST 3.5% Ex-Wharf New York      CLOSE   
45  AAXYO00                  Marine Gasoil 0.1% Dlvd Singapore      CLOSE   
46  AAXYR00                   Marine Gasoil 0.1% Dlvd Shanghai      CLOSE   
47  AAXYS00                Marine Gasoil 0.1% Dlvd South Korea      CLOSE   
48  PUAEO00         Bunker FO 380 CST 3.5% Ex-Wharf French Med      CLOSE   
49  POABX00             Marine Gasoil 0.1% Ex-Wharf French Med      CLOSE   
50  PUAGX00                 Bunker FO 180 CST 3.5% Dlvd Durban      CLOSE   
51 

In [25]:
def classify_location(location):
    location_to_info = {
        "NWE Cargo": ("North West Europe", "Europe"),
        "Med Cargo $": ("Mediterranean", "Europe"),
        "Med Cargo": ("Mediterranean", "Europe"),
        "Gibraltar": ("Gibraltar Strait", "Europe"),
        "Gulf Cargo": ("United States", "North America"),
        "Rdam Barge": ("Netherlands", "Europe"),
        "ARA Barge": ("Netherlands/Belgium", "Europe"),
        "Hamburg": ("Germany", "Europe"),
        "Gothenburg": ("Sweden", "Europe"),
        "Malta": ("Malta", "Europe"),
        "Piraeus": ("Greece", "Europe"),
        "Genoa": ("Italy", "Europe"),
        "Rotterdam": ("Netherlands", "Europe"),
        "Rdam": ("Netherlands", "Europe"),
        "South Korea": ("South Korea", "Asia"),
        "Busan": ("South Korea", "Asia"),
        "West Japan": ("Japan", "Asia"),
        "Japan": ("Japan", "Asia"),
        "Tokyo Bay": ("Japan", "Asia"),
        "Shanghai": ("China", "Asia"),
        "Hong Kong": ("China", "Asia"),
        "Spore Cargo": ("Singapore", "Asia"),
        "Singapore": ("Singapore", "Asia"),
        "Colombo": ("Sri Lanka", "Asia"),
        "Fujairah": ("United Arab Emirates", "Asia"),
        "Istanbul": ("Turkey", "Asia/Europe"),
        "St Petersburg": ("Russia", "Asia/Europe"),
        "New York": ("United States", "North America"),
        "Los Angeles": ("United States", "North America"),
        "Seattle": ("United States", "North America"),
        "San Francisco": ("United States", "North America"),
        "Charleston": ("United States", "North America"),
        "Norfolk": ("United States", "North America"),
        "Houston": ("United States", "North America"),
        "Savannah": ("United States", "North America"),
        "Panama Canal": ("Panama", "North America"),
        "Balboa": ("Panama", "North America"),
        "Santos": ("Brazil", "South America"),
        "Valparaiso": ("Chile", "South America"),
        "El Callao": ("Peru", "South America"),
        "Durban": ("Durban", "Africa"),
        "Algeciras": ("Spain", "Europe"),
        "Antwerp": ("Belgium", "Europe"),
        "Arab Gulf Cargo": ("Arab", "Asia")
    }
    return location_to_info.get(location, ("Unknown", "Unknown"))

# classify_location 함수를 사용하여 Country와 Continent 컬럼 추가
data[['Country', 'Continent']] = data['Location'].apply(lambda x: pd.Series(classify_location(x)))
data

Code                                         Assessment Statistics  \
0   PPXDK00                   FO 380 CST 3.5%S FOB Spore Cargo      CLOSE   
1   PUABC00                            FO 3.5%S FOB Rdam Barge      CLOSE   
2   PUAFT00                   Bunker FO 380 CST Dlvd Singapore      CLOSE   
3   AALMZ00                  Marine Gasoil 0.5% Dlvd Singapore      CLOSE   
4   PUAFN00              Bunker FO 380 CST 3.5% Dlvd Rotterdam      CLOSE   
5   AAYWT00  Gasoil .1%S (1000ppm) FOB ARA Barge (NextGen MOC)      CLOSE   
6   AARTG00                  Marine Gasoil 0.1% Dlvd Rotterdam      CLOSE   
7   AARKD00                    Bunker FO 380 CST Dlvd Shanghai      CLOSE   
8   AARKE00                   Marine Gasoil 0.5% Dlvd Shanghai      CLOSE   
9   PUAFL00                Bunker FO 380 CST 3.5% Dlvd Piraeus      CLOSE   
10  POADG00                    Marine Gasoil 0.1% Dlvd Piraeus      CLOSE   
11  PUAER00                   Bunker FO 380 CST Dlvd Hong Kong      CLOSE   
12  AAXYQ00                  Marine Gasoil 0.1% Dlvd Hong Kong      CLOSE   
13  PUAFD00              Bunker FO 380 CST 3.5% Ex-Wharf Genoa      CLOSE   
14  PBABK00                  Marine Gasoil 0.1% Ex-Wharf Genoa      CLOSE   
15  PUAGQ00                       Bunker FO 380 CST Dlvd Busan      CLOSE   
16  AARKJ00                      Marine Gasoil 0.5% Dlvd Busan      CLOSE   
17  AAMNV00             Bunker FO 380 CST 3.5% Dlvd Charleston      CLOSE   
18  AAWWV00                 Marine Gasoil 0.1% Dlvd Charleston      CLOSE   
19  AAGPM00            Bunker FO 380 CST 3.5% Dlvd Los Angeles      CLOSE   
20  AAWWY00                Marine Gasoil 0.1% Dlvd Los Angeles      CLOSE   
21  PBAAP00        Bunker FO 380 CST 3.5% Ex-Wharf Los Angeles      CLOSE   
22  AAWYR00            Marine Gasoil 0.1% Ex-Wharf Los Angeles      CLOSE   
23  AAGPD00                Bunker FO 380 CST 3.5% Dlvd Houston      CLOSE   
24  AAWWX00                    Marine Gasoil 0.1% Dlvd Houston      CLOSE   
25  AAGQN00               Bunker FO 380 CST 3.5% Dlvd New York      CLOSE   
26  AAWYB00                   Marine Gasoil 0.1% Dlvd New York      CLOSE   
27  AAGQW00                Bunker FO 380 CST 3.5% Dlvd Norfolk      CLOSE   
28  AAWYC00                    Marine Gasoil 0.1% Dlvd Norfolk      CLOSE   
29  AAXJR00           Bunker FO 380 CST 3.5% Ex-Wharf Savannah      CLOSE   
30  AAWZF00               Marine Gasoil 0.1% Ex-Wharf Savannah      CLOSE   
31  AAGSG00                Bunker FO 380 CST 3.5% Dlvd Seattle      CLOSE   
32  AAWYL00                    Marine Gasoil 0.1% Dlvd Seattle      CLOSE   
33  AAKAB00              Bunker FO 380 CST 3.5% Dlvd Gibraltar      CLOSE   
34  AARSU00                  Marine Gasoil 0.1% Dlvd Gibraltar      CLOSE   
35  PUAEV00                       Bunker FO 380 CST Dlvd Japan      CLOSE   
36  POACI00                      Marine Diesel 0.5% Dlvd Japan      CLOSE   
37  PBABW00                  Marine Gasoil 0.1% Dlvd El Callao      CLOSE   
38  PUAYR00             Bunker FO 380 CST 3.5% Dlvd Valparaiso      CLOSE   
39  PBABX00                 Marine Gasoil 0.1% Dlvd Valparaiso      CLOSE   
40  PUBAD00             Bunker FO 380 CST 3.5% Ex-Wharf Balboa      CLOSE   
41  AAXWI00           Marine Gasoil 0.1% Ex-Wharf Panama Canal      CLOSE   
42  AARKK00                    Marine Gasoil 0.5% Dlvd Colombo      CLOSE   
43  AAWYU00               Marine Gasoil 0.1% Ex-Wharf New York      CLOSE   
44  PUAFI00           Bunker FO 380 CST 3.5% Ex-Wharf New York      CLOSE   
45  AAXYO00                  Marine Gasoil 0.1% Dlvd Singapore      CLOSE   
46  AAXYR00                   Marine Gasoil 0.1% Dlvd Shanghai      CLOSE   
47  AAXYS00                Marine Gasoil 0.1% Dlvd South Korea      CLOSE   
48  PUAEO00         Bunker FO 380 CST 3.5% Ex-Wharf French Med      CLOSE   
49  POABX00             Marine Gasoil 0.1% Ex-Wharf French Med      CLOSE   
50  PUAGX00                 Bunker FO 180 CST 3.5% Dlvd Durban      CLOSE   
51 

In [26]:
data.to_csv('./assessment_classification.csv', index=False)